name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake --no-progress
          cmake --version

      - name: Configure CMake
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. -A x64

      - name: Build
        shell: cmd
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: libultrahdr-windows
          path: build/Release/*.exe
